"""empty message

Revision ID: 1a70d6a03415
Revises: 13942e121aa8
Create Date: 2025-08-05 18:50:18.261034

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a70d6a03415'
down_revision = '13942e121aa8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('media_url', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('media_public_id', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stories', schema=None) as batch_op:
        batch_op.drop_column('media_public_id')
        batch_op.drop_column('media_url')

    # ### end Alembic commands ###
