"""empty message

Revision ID: 51e9219290c4
Revises: 9c111ee1d32d
Create Date: 2025-07-22 18:30:12.324654

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '51e9219290c4'
down_revision = '9c111ee1d32d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', postgresql.ENUM('admin', 'user', name='role'), autoincrement=False, nullable=False))

    # ### end Alembic commands ###
